name: Hello
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
      - run: ls
      - uses: actions/checkout@v7.0.1
      - run: |
          pwd
          ls
          node -v
          java --version
          python -v
          npm -v
          curl https://mise.run | sh
          mise use --global node@lts
          mise use --global pnpm@11.7.0
          mise exec pnpm -- pnpm -v
          mise exec pnpm -- pnpm setup
          source ~/.bashrc 
          mise exec pnpm -- pnpm config set minimum-release-age 30240 --global  
          pnpm add -g @aikidosec/safe-chain
          safe-chain setup
          pnpm config set --global ignoreScripts true
      # - name: secret test
      #   shell: bash
      #   with:
      #     the_test_secret: ${{ secrets.TEST_SECRET }}
      #   run: echo "$the_test_secret"
