name: Hello
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
      - run: ls
      - uses: actions/checkout@v7.0.1
      - run: pwd
      - run: ls
      # - name: secret test
      #   shell: bash
      #   with:
      #     the_test_secret: ${{ secrets.TEST_SECRET }}
      #   run: echo "$the_test_secret"
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$SUPER_SECRET" > test.txt
          cat test.txt
